openapi: 3.0.0
info:
  title: Refertazione
  version: '1.0'
  license:
    name: Apache 2.0
  contact:
    name: Multimedia s.r.l.
    url: 'http://mm-multimedia.it/'
  description: "metodi per la gestione dell'applicativo di Refertazione"
servers:
  - url: 'http://emedtest:8080/eintegration'
paths:
  '/referto/accettazione/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of acceptance
    get:
      operationId: '10'
      summary: GET referti per ID accettazione
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/reportlite.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      description: metodo per cercare referti per id accettazione
  /referto:
    post:
      operationId: '9'
      summary: POST referto
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/medicalreporting/reportpost.v1.yaml
        description: object report to save on server
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reportId:
                    type: string
                required:
                  - reportId
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: motodo per introdurre un nuovo referto per accettazione e prestazioi
    parameters: []
  '/referto/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of report
    get:
      operationId: '8'
      summary: GET referto per ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/medicalreporting/report.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      description: "metodo per tornare il referto dato l'id"
  '/sede/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of units
    get:
      operationId: '7'
      summary: GET sede per ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/medicalreporting/unit.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
        - schema:
            type: string
          in: query
          name: id
          description: identify of unit
      description: metodo per trovare la sede per id
  '/operatore/prestazioni/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of operator
    get:
      operationId: '6'
      summary: GET prestazioni per ID operatore
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/activity.v1.yaml
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
          description: Not Found
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      description: "metodo per trovare tutte le prestazioni erogabili dal'operatore sanitario per id dell'operatore."
  '/operatore/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of operator
    get:
      operationId: '5'
      summary: GET operatore per ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/medicalreporting/person.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      description: "metodo per trovare l'operatore per id"
  '/operatore/cf/{cf}':
    parameters:
      - schema:
          type: string
        name: cf
        in: path
        required: true
        description: fiscal code of operator
    get:
      operationId: '4'
      summary: GET operatore per Codice Fiscale
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/person.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      description: "metodo per trovare l'operatore per codice fiscale."
  '/paziente/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of patient
    get:
      operationId: '3'
      summary: GET paziente per ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/medicalreporting/person.v1.yaml
        '401':
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
            application/xml:
              schema:
                $ref: ../common/models/error.v1.yaml
          description: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: "metodo per cercare il paziente per id (l'id del paziente è presente nalla accettazione o appuntamento già tornato con altri metodi)."
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
  '/accettazione/operatore/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of operator
    get:
      operationId: '2'
      summary: GET accettazioni per ID operatore
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/acceptance.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: query
          name: day
          description: day of acceptance
          required: true
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      description: "metodo per trovare le accettazioni legate all'operatore per id dell'operatore."
  '/prenotazioni/operatore/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: server id of operator
    get:
      operationId: '1'
      summary: GET prenotazioni per ID operatore
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/appointment.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: query
          name: day
          description: day of appointment
          required: true
        - schema:
            type: string
          in: header
          name: token
          description: authentication token
          required: true
      description: "metodo per trovare le prenotazioni legate all'operatore per id dell'operatore"
  '/paziente/cf/{cf}':
    get:
      operationId: '11'
      summary: GET paziente per CF
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/person.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: Questo metodo torna la lista dei pazienti che conincidono con il cf passato
    parameters:
      - schema:
          type: string
        name: cf
        in: path
        required: true
  '/azienda/{cfpiva}':
    get:
      summary: GET aziende per CF/PIVA
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/medicalreporting/companywithlocations.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: Ritorna la lista delle aziende per cf/p.iva
      operationId: '12'
    parameters:
      - schema:
          type: string
        name: cfpiva
        in: path
        required: true
  '/azienda/dipendenti/{cfipiva}':
    get:
      summary: "GET dipendenti per CF/PIVA dell'azienda"
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/worker.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: "Ritorna i lavoratori per il cf/p.iva dell'azienda passato in ingresso"
      operationId: '14'
    parameters:
      - schema:
          type: string
        name: cfipiva
        in: path
        required: true
  '/azienda/checkup/scaduti/{cfpiva}':
    get:
      summary: "GET checkup scaduti per CF/PIVA dell'azienda"
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/checkup.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: "Ritorna i dipendenti e le prestazioni dei checkup che sono scaduti per cf/p.iva dell'azienda"
      operationId: '13'
    parameters:
      - schema:
          type: string
        name: cfpiva
        in: path
        required: true
  '/azienda/dipendente/mansioni/{id}':
    get:
      summary: GET mansioni per ID del dipendente
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/medicalreporting/role.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: ritorna la lista delle mansioni del dipendente ricercato per id
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ''
