openapi: 3.0.0
info:
  title: Login
  version: '1.0'
  contact:
    name: Multimedia s.r.l.
    url: 'http://mm-multimedia.it/'
  description: method for authentication of user
  license:
    name: Apache 2.0
servers:
  - url: 'http://emedtest:8080/eintegration'
paths:
  /authenticate:
    post:
      operationId: '1'
      summary: POST Authentication
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/login/authenticatedata.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/login/user.v1.yaml
        description: user for login
      description: login with return of token
    parameters: []
